### ISSUE TITLE
can't build with docker

### ISSUE THREAD

**Issue by subproc** [talex5/qubes-mirage-firewall#11]
hi, trying to build qubes-mirage-firewall, but when i run ./build-with-docker.sh it say me:

"Step 1 : FROM ocaml/opam:debian-8_ocaml-4.03.0
 ---> b2670142ae16
Step 2 : RUN cd opam-repository && git reset --hard 0f17b354206c97e729700ce60ddce3789ccb1d52 && opam update
 ---> Running in d8f345e51440
fatal: Could not parse object '0f17b354206c97e729700ce60ddce3789ccb1d52'.
The command '/bin/sh -c cd opam-repository && git reset --hard 0f17b354206c97e729700ce60ddce3789ccb1d52 && opam update' returned a non-zero code: 128"

what can i do? thanks

**Comment by talex5** [comment]
Do you have an out-of-date base image? Try:
```
docker pull ocaml/opam:debian-8_ocaml-4.03.0
```
