### ISSUE TITLE
Must set virt_mode to 'pv' on Qubes R4

### ISSUE THREAD

**Issue by reynir** [talex5/qubes-mirage-firewall#23]
On Qubes R4-rc3 I had to set the `virt_mode` to `pv` instead of `hvm` for the mirage-firewall qube/vm.

**Comment by talex5** [comment]
That sounds right. I don't use Qubes R4 yet... could you suggest some wording for the README to explain to people how to do this?

**Comment by reynir** [comment]
Yes, I can write some words (later) about setting up mirage-firewall in R4. There are other changes as well such as `ProxyVM` no longer being a thing, etc., so a R4-specific section would probably be necessary. I have been using Qubes for about a day, so a review of whatever I write would be appreciated :-)

**Comment by talex5** [comment]
Thanks. I see there is more discussion at https://groups.google.com/forum/#!msg/qubes-users/5apbM_E0prc/mLaNzQJOAgAJ - some clear instructions in the README would be great!
