### ISSUE TITLE
Is it supposed to work in Qubes 4?

### ISSUE THREAD

**Issue by najamelan** [talex5/qubes-mirage-firewall#25]
I tried to follow the steps from the readme to install the binary release.

One thing to note is that the create new VM does not have ProxyVM. So I picked standalone not from template.

When I try to launch it with qvm-start, I briefly get a window showing booting from rom, which then closes and the vm with it.

The log files do show "cannot connect to qrexec" "cannot connect to gui-daemon" "cannot connect to qubesdb".

**Comment by talex5** [comment]
See https://github.com/talex5/qubes-mirage-firewall/issues/23 and the instructions at https://groups.google.com/d/msg/qubes-users/5apbM_E0prc/EPPI-qyCBAAJ.

Various Qubes 4 users have said they're planning to send an update to the README for this, but you could get there first if you're quick :-)
