### ISSUE TITLE
How to restrict outbound connections from appvms

### ISSUE THREAD

**Issue by archpaladin1** [talex5/qubes-mirage-firewall#30]
Hello,

I'm trying to figure out how to configure this firewall to restrict connections between an appvm and a list of allowed IP addresses (or hostnames, more preferably).  Any other outbound connection should be rejected.

I thought that changing the rules.ml file to be the following would work:
```
let allowed_addr = Ipaddr.V4.of_string_exn "XXX.XXX.XXX.XXX"
let from_client = function
  | { dst = `NetVM } -> `NAT
  | { dst = allowed_addr } -> `NAT
  | { dst = `Client_gateway; proto = `UDP { dport = 53 } } -> `NAT_to (`NetVM, 53)
  | { dst = (`Client_gateway | `Firewall_uplink) } -> `Drop "packet addressed to firewall itself"
  | { dst = `Client _ } -> `Drop "prevent communication between client VMs"
```
In fact this appears to do nothing.  All outbound connections are still allowed.

Can you give an example of how to restrict outbound connections?  We can assume that all appvms connected to this firewall will have the same restrictions, so no need to identify a particular client.

**Comment by talex5** [comment]
You're nearly right!

`{ dst = allowed_addr } ->` creates a *new* variable `allowed_addr` and sets it to whatever the destination was. You need to use a different variable, and then compare it with `allowed_addr`.

e.g. something like

`{ dst } when dst = allowed_addr ->` 

I'm a bit surprised the compiler didn't warn about this :-(

**Comment by archpaladin1** [comment]
Thanks - I'm new to OCaml so I'm still getting used to the syntax.

This worked pretty well for one host:

```
let allowed_addrs = Ipaddr.V4.of_string_exn "XXX.XXX.XXX.XXX"

let from_client = function
  | { dst = `NetVM } -> `NAT
  | { dst = `External e } when e = Ipaddr.V4 allowed_addrs -> `NAT
  | etc...
```

So the follow-on question is how do I expand `allowed_addrs` to be a list?  For example:
```
let allowed_addrs = [ Ipaddr.V4.of_string_exn "XXX.XXX.XXX.XXX" ; Ipaddr.V4.of_string_exn "YYY.YYY.YYY.YYY" ]

let from_client = function
  | { dst = `NetVM } -> `NAT
  | { dst = `External e } when $WTF_GOES_HERE -> `NAT
  | etc...
```

**Comment by cfcs** [comment]
Maybe something like
```ocaml
(* stuff above *)
  | { dst = `External e } when List.mem e allowed_addrs -> `NAT
```

**Comment by archpaladin1** [comment]
List.mem is probably correct, but I'm still running into syntax issues because there's a variable typing problem.  The compiler throws:
```
Error: This expression has type Ipaddr.V4.t list
       but an expression was expected of type Ipaddr.t list
       Type Ipaddr.V4.t is not compatible with type
         Ipaddr.t = (Ipaddr.V4.t, Ipaddr.V6.t) Ipaddr.v4v6
```

If I add in the explicit type, like so:
```
  | { dst = `External e } when List.mem e Ipaddr.V4 allowed_addrs -> `NAT
```
I get this:
```
Error: This function has type 'a -> 'a list -> bool
       It is applied to too many arguments; maybe you forgot a `;'.
```
And I can't figure out where a semicolon is supposed to go.

I'm sure this is a simple problem, but there seems to be a dearth of readable OCaml documentation online.

**Comment by cfcs** [comment]
@archpaladin1 it looks like `External` is something like
```ocaml
[ `External of Ipaddr.t ]
```

`Ipaddr.V4` deals with IPv4-addresses, `Ipaddr.V6` - `Ipaddr.t` can contain both the `V4.t` and `V6.t` types.

The reason your `when e = Ipaddr.V4 allowed_addrs` worked for the single case is that there are two things called `Ipaddr.V4`: The **module**, and the **constructor** belonging to the `Ipaddr.t` type.
`Ipaddr.t` is defined something like:
```ocaml
type t =
  | V4 of Ipaddr.V4.t
  | V6 of Ipaddr.V6.t
```
So when you do `Ipaddr.V4 my_ip` it takes an argument of the `Ipaddr.V4.t` type and "wraps it into" a `Ipaddr.t` type.

In this case your `External e` can also be an IPv6 address, so that is what we need to handle.

So err you should be able to do something like this:

```ocaml
let allowed_addrs = List.map Ipaddr.of_string_exn
  [ "XXX.XXX.XXX.XXX" ; 
    "YYY.YYY.YYY.YYY"
  ]

let from_client = function
  | { dst = `NetVM } -> `NAT
  | { dst = `External ip } when List.mem ip allowed_addrs -> `NAT
  (* | etc... *)
```

**Comment by archpaladin1** [comment]
That worked, thanks!

I'll see if I can work some edits into my copy of the code to smooth out some documentation and make a pull request.

It would be great if we could set up the firewall to be based on hostnames rather than IP addresses, but I think that will require some recoding.

**Comment by cfcs** [comment]
@archpaladin1 By the way, I wrote a patch to enable users to specify policies using a JSON syntax.
The branch is here: https://github.com/cfcs/qubes-mirage-firewall/tree/user_supplied_rules
It may be a little bit out of date regarding upstream patches, but if you're feeling adventurous you could have a look at that.

**Comment by archpaladin1** [comment]
Okay - I didn't go through the whole fork & commit process for just a few changes, but here's my suggestion for an updated file:

[https://pastebin.com/p20CAu7T](url)
