### ISSUE TITLE
build with docker failing

### ISSUE THREAD

**Issue by xaki23** [talex5/qubes-mirage-firewall#34]
this is not the fixed-yesterday debian-8-container issue.
this is the new debian-9 container failing.
i am super-unfamiliar with docker, so i might be getting some of the terms wrong... 

it seems to pull/download the same docker fragments twice. 
then runs out of space. (afaict _not_ in the buildvm)

build log, with some boring middle sections stripped:
------------------------------------------------------------------------
Sending build context to Docker daemon 121.9 kB
Step 1/9 : FROM ocaml/opam2@sha256:feebac4b6f9df9ed52ca1fe7266335cb9fdfffbdc0f6ba4f5e8603ece7e8b096
Trying to pull repository docker.io/ocaml/opam2 ... 
sha256:feebac4b6f9df9ed52ca1fe7266335cb9fdfffbdc0f6ba4f5e8603ece7e8b096: Pulling from docker.io/ocaml/opam2
bc9ab73e5b14: Pulling fs layer
26d9a6276145: Pulling fs layer
[...]
601d12a29a64: Verifying Checksum
601d12a29a64: Download complete
Trying to pull repository registry.fedoraproject.org/ocaml/opam2 ... 
Trying to pull repository quay.io/ocaml/opam2 ... 
Trying to pull repository registry.access.redhat.com/ocaml/opam2 ... 
Trying to pull repository registry.centos.org/ocaml/opam2 ... 
Trying to pull repository docker.io/ocaml/opam2 ... 
sha256:feebac4b6f9df9ed52ca1fe7266335cb9fdfffbdc0f6ba4f5e8603ece7e8b096: Pulling from docker.io/ocaml/opam2
bc9ab73e5b14: Pulling fs layer
26d9a6276145: Pulling fs layer
[...]
601d12a29a64: Verifying Checksum
601d12a29a64: Download complete
failed to register layer: Error processing tar file(exit status 1): write /home/opam/.opam/4.04/bin/ocamldoc.opt: no space left on device

**Comment by talex5** [comment]
`no space left on device` means that your computer is out of disk space, at least on the partition with the Docker state. `df -h` will show which filesystem it is.

If Docker itself is taking up too much space, try `docker system prune` to remove things you no longer need.

**Comment by xaki23** [comment]
i had already tried cranking up the buildvm private volume, which doesnt make a difference. (since that turns out to be the wrong place) 

/var/lib/docker is in the root volume, which is indeed low on space.
/var/lib/docker is taking up 2.1 GB, "docker system prune" does not free up space.
sifting through du output says most of the space is used in various overlay2/.../ocaml trees. 

the buildvm (+docker) were only used to build mirage-fw, but there were attempts both with the debian-8 and the debian-9 container.
so a default qubes rootfs has space for _one_ mirage-fw build-container, but not two.

freed up space by restarting buildvm.
now the build-with-docker process gets along further, but fails with out-of-space again while building the ocaml modules.

so whats the recommended vm configuration to run the build in these days?
do i need to make it a standalonevm so i can crank up system volume from the default 10GB?
(note the deb8 based container build worked fine in a default sized appvm)

**Comment by xaki23** [comment]
losing state is actualy semi-intentional there, my usual qubes-mirage-build wouldnt use the docker path either, but is broken right now for some xen-pkg related reasons.

anyways, build with docker some more, now (with symlink) it doesnt run out of space anymore, builds stuff a lot. then fails hard near what looks like endgame linking:

--------------
File "unikernel.ml", line 1:
Error: The files /home/opam/.opam/4.04/lib/mirage-qubes/qubes.cmi
       and uplink.cmi make inconsistent assumptions over interface Qubes
Command exited with code 2.
run ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tags'
     'predicate(mirage_xen),warn(A-4-41-42-44),debug,bin_annot,strict_sequence,principal,safe_string'
     '-pkgs'
     'cstruct,functoria-runtime,lwt,mirage-clock-freestanding,mirage-logs,mirage-nat,mirage-net-xen,mirage-qubes,mirage-runtime,mirage-types,mirage-types-lwt,mirage-xen,netchannel,shared-memory-ring,tcpip,tcpip.arpv4,tcpip.stack-direct,tcpip.xen,vchan'
     '-cflags' '-g' '-lflags'
     '-g,-dontlink,unix,-dontlink,str,-dontlink,num,-dontlink,threads'
     '-tag-line' '<static*.*>: warn(-32-34)' '-X' '_build-solo5-hvt' '-X'
     '_build-ukvm' 'main.native.o']: exited with 10
Makefile:18: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by talex5** [comment]
You've probably got some stale files in `_build`. Try deleting that directory first.

I just tried the build on a fresh disposable Fedora 28 VM on Qubes 4 (with the symlink), and it worked for me.

**Comment by xaki23** [comment]
can confirm it now builds-with-docker 
- on a clean/new fc28 appvm 
- with a clean/new git clone 
- and varlibdocker symlinked to userhome. 

"stale files in _build" is somewhat unexpected, in particular the part where the build-in-a-clean-custom-env process brings along external build state of any kind.

**Comment by talex5** [comment]
( It uses `_build` so incremental builds are fast - it helps if you're making lots of changes. Eventually Mirage will move to a better build system (dune) that automatically rebuilds when a library it depends on changes, rather than failing with the `inconsistent assumptions` message. )
